### Pandas

In [1]:
import pandas as pd
import numpy as np

#### 改变dataframe中列的名字

In [2]:
d = {
        'one': [1, 2, 3, 4, 5],
        'two': [9, 8, 7, 6, 5],
        'three': ['a', 'b', 'c', 'd', 'e']
    }
df = pd.DataFrame(d)

names = df.columns.tolist()
names[names.index('two')] = 'new_name'
df.columns = names

print(df)

   one  new_name three
0    1         9     a
1    2         8     b
2    3         7     c
3    4         6     d
4    5         5     e


#### 对axis=0和axis=1的理解

In [3]:
df = pd.DataFrame([[1, 5, 1, 1], [2, 6, 2, 2], [3, 7, 3, 3]], columns=["col1", "col2", "col3", "col4"])
print(df)
print(df.mean(axis=1))
print(df.drop('col4', axis=1))

# 理解axis有问题，df.mean其实是在每一行上取所有列的均值，而不是保留每一列的均值。
# 也许简单的来记就是axis=0代表往跨行（down)，而axis=1代表跨列（across)

# 换句话说:
# 使用0值表示沿着每一列或行标签\索引值向下执行方法
# 使用1值表示沿着每一行或者列标签模向执行对应的方法

   col1  col2  col3  col4
0     1     5     1     1
1     2     6     2     2
2     3     7     3     3
0    2.0
1    3.0
2    4.0
dtype: float64
   col1  col2  col3
0     1     5     1
1     2     6     2
2     3     7     3


In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

scaler1 = StandardScaler()
print(scaler1.fit(df))
print(scaler1.mean_)
print(scaler1.transform(df))

StandardScaler(copy=True, with_mean=True, with_std=True)
[2. 6. 2. 2.]
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]


In [5]:
scaler2 = scale(df, axis=0)  # axis=0 by default
print(scaler2)
scaler2 = scale(df, axis=1)
print(scaler2)

[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]
[[-0.57735027  1.73205081 -0.57735027 -0.57735027]
 [-0.57735027  1.73205081 -0.57735027 -0.57735027]
 [-0.57735027  1.73205081 -0.57735027 -0.57735027]]


### Numpy

#### 找出值为NA的位置

In [6]:
x = np.random.random((5,3))
x[0,1] = np.nan
x[4,2] = np.nan
print(x)

y = np.where(np.isnan(x))
x[y]

[[0.24951758        nan 0.16429865]
 [0.84203533 0.21122092 0.31908049]
 [0.90498805 0.9921118  0.79555363]
 [0.2750694  0.08656978 0.55364398]
 [0.98072927 0.79598424        nan]]


array([nan, nan])